version: '3'
services:
  api:
    build:
      context: .
      args:
        JAR_FILE: target/challenge-1.0.0.jar
    ports:
      - "8080:8080"
    links:
      - redis
    environment:
      - REDIS_HOSTNAME=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    volumes:
      - ./data:/data
    expose:
      - 6379
    ports:
      - "6379:6379"
